baseURL = "http://forsyte.at/"
languageCode = "en-us"
title = "FORSYTE"

[taxonomies]
  group = "groups"
  role = "roles"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable caches for getcsv, getjson, getresource.
# Otherwise, we would cache e.g. person information JSON files from TISS in /tmp/hugo_cache, so we wouldn't
# notice when people change their profile pictures and still link to the old defunct picture location.
[caches]
  [caches.getcsv]
    maxAge = "5m"
  [caches.getjson]
    maxAge = "5m"
  [caches.getresource]
    maxAge = "5m"
