baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[taxonomies]
  group = "groups"
  role = "roles"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
