baseURL = "http://forsyte.at/"
languageCode = "en-us"
title = "FORSYTE"

[taxonomies]
  group = "groups"
  role = "roles"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
